version: '3.7'

services:
  omekas:
    build: ./
    volumes:
      - ./modules/:/var/www/html/modules/
      - ./themes/custom/:/var/www/html/themes/custom/
    ports:
      - 80:80
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:10.4.10-bionic
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka
    restart: always

  db_admin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    restart: always
